export const borderRadiusValuesTokens = [
  "none",
  "3xs",
  "2xs",
  "xs",
  "sm",
  "lg",
  "md",
  "xl",
  "2xl",
  "3xl",
  "4xl",
  "pill",
] as const;

export const borderWidthValuesTokens = ["xs", "sm", "md"] as const;

export const dimensionValuesTokens = [
  0, 25, 50, 100, 150, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200,
  1300, 1400, 1500, 1600, 1700, 1800, 1900,
] as const;

export const spacingValuesTokens = [
  "4xs",
  "3xs",
  "2xs",
  "xs",
  "sm",
  "md",
  "lg",
  "xl",
  "2xl",
  "3xl",
  "4xl",
] as const;

export const fontFamilyTokens = ["headline", "content"] as const;

export const fontHeightTokens = [
  "4xl",
  "3xl",
  "2xl",
  "xl",
  "lg",
  "md",
  "base",
  "sm",
  "xs",
] as const;

export const fontParagraphSpacingTokens = ["base"] as const;

export const colorValuesTokens = [
  "primary",
  "secondary",
  "accent",
  "success",
  "information",
  "error",
  "warning",
  "neutral-dark",
  "neutral-light",
] as const;

export const fontValuesTokens = [
  "label",
  "labelLong",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hyperlink",
  "hyperlinkHover",
  "caption",
  "body",
  "bodyShort",
  "bodyLong",
] as const;

export const fontSizeTokens = [
  "4xl",
  "3xl",
  "2xl",
  "xl",
  "lg",
  "md",
  "base",
  "sm",
  "xs",
] as const;

export const fontSpacingTokens = ["lg", "md", "xs", "base"] as const;

export const fontWeightTokens = [
  "regular",
  "medium",
  "semiBold",
  "bold",
] as const;

export const themePaletteSurfaceTokens = [
  "primary-default",
  "primary-defaultHover",
  "primary-defaultSubtle",
  "primary-defaultSubtleHover",
  "primary-defaultSubtleHoverAlt",
  "secondary-default",
  "secondary-defaultHover",
  "secondary-defaultSubtle",
  "secondary-defaultSubtleHover",
  "disabled-default",
  "error-default",
  "error-defaultHover",
  "error-defaultSubtle",
  "error-defaultSubtleHover",
  "success-default",
  "success-defaultHover",
  "success-defaultSubtle",
  "success-defaultSubtleHover",
  "information-default",
  "information-defaultHover",
  "information-defaultSubtle",
  "information-defaultSubtleHover",
  "warning-default",
  "warning-defaultHover",
  "warning-defaultSubtle",
  "warning-defaultSubtleHover",
  "default",
  "page",
  "pageAlternative",
  "alternative",
] as const;

export const themePaletteTextTokens = [
  "primary-onColor",
  "primary-onColorHover",
  "primary-onColorSubtle",
  "primary-onColorSubtleHover",
  "primary-default",
  "primary-defaultHover",
  "secondary-onColor",
  "secondary-onColorHover",
  "secondary-onColorSubtle",
  "secondary-onColorSubtleHover",
  "secondary-default",
  "secondary-defaultHover",
  "disabled-default",
  "disabled-onColor",
  "error-onColor",
  "error-onColorHover",
  "error-onColorSubtle",
  "error-onColorSubtleHover",
  "error-default",
  "error-defaultHover",
  "success-onColor",
  "success-onColorHover",
  "success-onColorSubtle",
  "success-onColorSubtleHover",
  "success-default",
  "success-defaultHover",
  "information-onColor",
  "information-onColorHover",
  "information-onColorSubtle",
  "information-onColorSubtleHover",
  "information-default",
  "information-defaultHover",
  "warning-onColor",
  "warning-onColorHover",
  "warning-onColorSubtle",
  "warning-onColorSubtleHover",
  "warning-default",
  "warning-defaultHover",
  "default-body",
  "default-hero",
  "default-heading",
  "default-caption",
  "default-placeholder",
  "onColor-hero",
  "onColor-heading",
  "onColor-body",
  "onColor-caption",
  "onColor-placeholder",
  "accent-onColor",
  "accent-onColorHover",
  "accent-onColorSubtle",
  "accent-onColorSubtleHover",
  "accent-default",
  "accent-defaultHover",
] as const;

export const themePaletteIconTokens = [
  "primary-onColor",
  "primary-onColorHover",
  "primary-onColorSubtle",
  "primary-onColorSubtleHover",
  "primary-default",
  "primary-defaultHover",
  "primary-defaultSubtle",
  "primary-defaultSubtleHover",
  "secondary-onColor",
  "secondary-onColorHover",
  "secondary-onColorSubtle",
  "secondary-onColorSubtleHover",
  "secondary-default",
  "secondary-defaultHover",
  "disabled-default",
  "disabled-onColor",
  "error-onColor",
  "error-onColorHover",
  "error-onColorSubtle",
  "error-onColorSubtleHover",
  "error-default",
  "error-defaultHover",

  "success-onColor",
  "success-onColorHover",
  "success-onColorSubtle",
  "success-onColorSubtleHover",
  "success-default",
  "success-defaultHover",

  "information-onColor",
  "information-onColorHover",
  "information-onColorSubtle",
  "information-onColorSubtleHover",
  "information-default",
  "information-defaultHover",

  "warning-onColor",
  "warning-onColorHover",
  "warning-onColorSubtle",
  "warning-onColorSubtleHover",
  "warning-default",
  "warning-defaultHover",
] as const;

export const themePaletteBorderTokens = [
  "primary-default",
  "primary-defaultHover",
  "primary-defaultSubtle",
  "primary-defaultSubtleHover",
  "primary-focus",
  "error-default",
  "error-defaultHover",
  "error-defaultSubtle",
  "error-defaultSubtleHover",
  "error-focus",
  "success-default",
  "success-defaultHover",
  "success-defaultSubtle",
  "success-defaultSubtleHover",
  "success-focus",
  "warning-default",
  "warning-defaultHover",
  "warning-defaultSubtle",
  "warning-defaultSubtleHover",
  "warning-focus",
  "information-default",
  "information-defaultHover",
  "information-defaultSubtle",
  "information-defaultSubtleHover",
  "information-focus",
  "secondary-default",
  "secondary-defaultHover",
  "secondary-defaultSubtle",
  "secondary-defaultSubtleHover",
  "secondary-focus",
  "disabled",
  "disabled-onColor",
  "default",
  "default-onColor",
] as const;

export const colorScaleValuesTokens = [
  100, 150, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200,
] as const;

export const colorScaleStringValuesTokens = [
  "100",
  "150",
  "200",
  "300",
  "400",
  "500",
  "600",
  "700",
  "800",
  "900",
  "1000",
  "1100",
  "1200",
] as const;
